@startuml initialMount(완료)
'http://localhost:3000/initSetting

title initialMount(완료) seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Move "/initSetting"

Client -> Server: **GET /users/prefereces** \n Request "Read UserPrefereces"

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink readUserPreferences_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/login"

else #LightYellow newUser_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **303**,
            comment: "**error comment**",
            message: "**error message**"
    end note

else #LightBlue readUserPreferences_success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**

    end note
    User <-- Client: Alert "이미 선호도가 설정됐습니다." \n & Redirect "/userHome"

end

@enduml