@startuml preferenceSubmission(완료)
'http://localhost:3000/initSetting

title preferenceSubmission(완료) seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Input "day_preference, time_preference" \n & Click "제출하기"

Client -> Server: **POST /users/preferences** \n Request "Create Preferences"
note right
    req.body:
        day_preference:
            Mon: 3,
            ...,
        time_preference:
            morning: 3,
            afternoon: 3,
            evening: 3
end note

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink createUserPreferences_redirectLogin
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/login"

else #Pink createUserPreferences_redirectUserHome
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **409**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "이미 선호도가 설정됐습니다." \n & Redirect "/userHome"

else #LightBlue createUserPreferences_success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **201**
    end note
    User <-- Client: Modal "Preference Survey Completed"
    User -> Client: Click "Start"
    User <-- Client: Redirect "/UserHome"

end

@enduml