@startuml updateUser(완료)
'http://localhost:3000/setting

title updateUser(완료) seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Click "변경사항 저장"

Client -> Server: **PATCH /users** \n Request "Update UserInformation"
note right
    req.body:
        user: {
            name: '홍승빈',
            password: '123456789',
            calendar_id: 'hongsb119@gmail.com'
        },
        preference: {
            day_preference: {
                Mon: 5,
                Tue: 5,
                Wed: 5,
                Thu: 5,
                Fri: 5,
                Sat: 5,
                Sun: 5,
            },
            time_preference: {
                morning: 1,
                afternoon: 1,
                evening: 1,
            },
        }
end note

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink updateUserInformation_userNotFound
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **404**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/login"

else #Pink updateUserInformation_accessDenied
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.message" \n & Redirect "/login"

else #Pink updateUserInformation_invaildRequest
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **400**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment"
    ' alt #Gray "선호도 형식이 올바르지 않습니다."
    '     User <-- Client: Alert "result.comment"

    ' else #Gray "로컬 로그인으로 인증된 계정만 사용할 수 있습니다."
    '     User <-- Client: Alert "result.comment"

    ' else #Gray "소셜 로그인으로 인증된 계정만 사용할 수 있습니다."
    '     User <-- Client: Alert "result.comment"

    ' end

else #LightYellow newUser_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **303**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Redirect "/initSetting"

else #LightBlue updateUserInformation_access
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**
    end note
    User <-- Client: Alert "사용자 정보가 수정됐습니다."
end

@enduml