@startuml moveViewAll
'http://localhost:3000/userHome

title moveViewAll seqeunce diagram

skinparam SequenceMessageAlignment center

participant Client order 20
actor User order 10

User -> Client: Click "View All"
User <-- Client: Redirect "/dashboard"

@enduml