@startuml allPageInitialMount(완료)
'http://localhost:3000/

title allPageInitialMount(완료) seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Move "/.."

Client -> Server: **GET /plans** \n Request "Update plans' status"

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink updatePlanStatus_failure
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **404**,
            comment: "**error comment**",
            message: "**error message**"
    end note

else #LightBlue updatePlanStatus_success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**
    end note

end

@enduml