@startuml moveRegistration
'http://localhost:3000/login

title moveRegistration seqeunce diagram

skinparam SequenceMessageAlignment center

participant Client order 20
actor User order 10

User -> Client: Click "가입하기"
User <-- Client: Redirect "/registration"

@enduml