@startuml initialMount(완료)
'http://localhost:3000/editVote/:id

title initialMount(완료) seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Move "/editSchedule/:id"

Client -> Server: **GET /groups/:group_id/plans/:plan_id** \n Request "Read PlanInformation"

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink readPlanInformation_planNotFound
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **404**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/group/:id"

else #Pink readPlanInformation_accessDenied
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.message" \n & Redirect "/login"

else #LightYellow newUser_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **303**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Redirect "/initSetting"

else #LightBlue readPlanInformation_success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**,
            plan:
                **id**,
                **vote_plan_time**,
                **status**,
    end note

    Client -> Server: **GET /groups/:group_id/plans/:plan_id/vote/:user_id** \n Request "Read userVote"

    alt#Gold #Pink internal_error
        Client <-- Server: Reponse "JSON"
        note left
            result:
                statusCode: **500**,
                comment: "**error comment**",
                message: "**error message**"
        end note
        User <-- Client: Alert "result.comment" & "result.message"

    else #Pink readUserVote_notFound
        Client <-- Server: Reponse "JSON"
        note left
            result:
                statusCode: **404**,
                comment: "**error comment**",
                message: "**error message**"
        end note
        alt #Gray "해당 그룹이 존재하지 않거나 그룹 참여자가 아닙니다."
            User <-- Client: Alert "result.comment" & Redirect "/userHome"

        else #Gray "제출된 투표가 없습니다."
            User <-- Client: Alert "result.comment" & Redirect "/vote/:id"
        
        end

    else #Pink readUserVote_accessDenied
        Client <-- Server: Reponse "JSON"
        note left
            result:
                statusCode: **401**,
                comment: "**error comment**",
                message: "**error message**"
        end note
        User <-- Client: Alert "result.message" \n & Redirect "/login"

    else #LightYellow newUser_redirect
        Client <-- Server: Reponse "JSON"
        note left
            result:
                statusCode: **303**,
                comment: "**error comment**",
                message: "**error message**"
        end note
        User <-- Client: Redirect "/initSetting"

    else #LightBlue readUserVote_success
        Client <-- Server: Reponse "JSON"
        note left
            result:
                statusCode: **200**,
                vote_plan_time: [{
                    **start**,
                    **end**,
                    **day**,
                    **time**,
                    **approval**
                }, ...]

        end note

    end

end

@enduml