@startuml initialMount
'http://localhost:3000/editSchedule

title initialMount seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Move "/editSchedule"

Client -> Server: **GET /groups/:group_id/plans/:plan_id/schedule/:user_id** \n Request "Read userSchedule"

alt#Gold #Pink Failure_internal
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink Failure
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **404**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "제출된 일정이 없습니다." \n & Redirect "/plan/:id"

else #Pink Failure_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.message" \n & Redirect "/login"

else #LightYellow Redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **303**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/initSetting"

else #LightBlue Success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**,
            submission_time_slot: [{
                **date**,
                **time_scope**: [{
                        **start**,
                        **end**,
                        **available**
                }, ...]
            }, ...]
    end note

end

@enduml