@startuml initialMount
'http://localhost:3000/editSchedule/:id

title initialMount seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Move "/editSchedule/:id"

Client -> Server: **GET /groups/:group_id/plans/:plan_id/schedule/:user_id** \n Request "Read userSchedule"

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink readUserSchedule_scheduleNotFound
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **404**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "제출된 일정이 없습니다." \n & Redirect "/plan/:id"

else #Pink readUserSchedule_accessDenied
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.message" \n & Redirect "/login"

else #LightYellow newUser_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **303**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Redirect "/initSetting"

else #LightBlue readUserSchedule_success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**,
            submission:
                **id**,
                **name**,
                **user_id**,
                **plan_id**,
                **submission_time_slot**
    end note

end

@enduml