@startuml updateSchedule(완료)
'http://localhost:3000/editSchedule/:id

title updateSchedule(완료) seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Click "일정 수정"

Client -> Server: **PATCH /groups/:group_id/plans/:plan_id/schedules** \n Request "Update UserSchedule"
note right
    req.body:
        submission_time_slot: [{
            date: "2024-11-01",
            time_scope: [
                {
                    start: "9:00",
                    end: "9:15",
                    available: true
                }
            ]
        }, ...]
end note

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink updateUserSchedule_notFound
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **404**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    alt #Gray "해당 그룹이 존재하지 않거나 그룹 참여자가 아닙니다."
        User <-- Client: Alert "result.comment" & Redirect "/userHome"

    else #Gray "일정을 제출할 약속이 없습니다."
        User <-- Client: Alert "result.comment" & Redirect "/group/:id"

    else #Gray "제출된 일정이 없습니다."
        User <-- Client: Alert "result.comment" & Redirect "/plan/:id"

    else #Gray "일정을 수정할 약속이 없습니다."
        User <-- Client: Alert "result.comment" & Redirect "/group/:id"

    end

else #Pink updateUserSchedule_accessDenied
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.message" \n & Redirect "/login"

else #Pink updateUserSchedule_invaildRequest
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **400**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment"

else #LightYellow newUser_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **303**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/initSetting"

else #LightBlue updateUserSchedule_success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**

    end note
    User <-- Client: Alert "일정이 수정됐습니다." \n & Redirect "/plan/:id"
end

@enduml