@startuml updateGroup(완료)
'http://localhost:3000/editGroup/:id

title updateGroup(완료) seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Click "변경사항 저장"

Client -> Server: **PATCH /groups/:group_id** \n Request "Update GroupInformation"
note right
    req.body:
        name: "**groupName**",
        invitationCode: "**invitationCode**",
        preference_setting: "**manual**" or "**auto**",
        manual_group_preference: {
            **day**: [...],     // scale: 0 ~ 6
            **time**: [...],    // scale: 0 ~ 2
        }
end note

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink updateGroupInformation_failure
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **404**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/userHome"

else #Pink updateGroupInformation_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.message" \n & Redirect "/login"

else #LightYellow newUser_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **303**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Redirect "/initSetting"

else #LightBlue updateGroupInformation_success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**
    end note
    User <-- Client: Alert "그룹 정보가 정상적으로 수정됐습니다."
end

@enduml