@startuml createVote(완료)
'http://localhost:3000/createVote/:id

title createVote(완료) seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Click "투표 생성"

Client -> Server: **POST /groups/:group_id/plans/:plan_id/failure** \n Request "Cancel Vote"
note right
    req.body:
        option: **select**
        vote_plan_time: [{
                **start**
                **end**
        }, ...],
        **vote_deadline**
end note

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink createVote_planNotFound
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **404**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/group/:id"

else #Pink createVote_notGroupLeader
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **403**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/plan/:id"

else #Pink createVote_accessDenied
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.message" \n & Redirect "/login"

else #LightYellow newUser_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **303**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Redirect "/initSetting"

else #LightBlue createVote_success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**
    end note
    User <-- Client: Redirect "/vote/:id"

end

@enduml