@startuml initialMount(완료)
'http://localhost:3000/login

title initialMount(완료) seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Move "/login"

Client -> Server: **GET /users** \n Request "Read UserInformation"

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink readUserInformation_failure
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401** or **404**,
            comment: "**error comment**",
            message: "**error message**"
    end note

else #LightYellow newUser_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **303**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Redirect "/initSetting"

else #LightBlue readUserInformation_success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**

    end note
    User <-- Client: Alert "이미 로그인 중입니다." \n & Redirect "/userHome"

end

@enduml