@startuml localLogin(완료)
'http://localhost:3000/login

title localLogin(완료) seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Input "email, password" \n & Click "로그인"

Client -> Server: **POST /users/login** \n Request "Local Login"
note right
    req.body:
        email: "**userEmail**",
        password: "**userPassword**"
end note

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink localLogin_failure
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **400** or **404**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment"

else #Pink localLogin_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **409**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/userHome"

else #LightBlue localLogin_success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **201**,
            name: **name**
    end note
    User <-- Client: Alert "user.name님, 환영합니다." \n & Redirect "/userHome"

end

@enduml