@startuml recommendPlanSchedule(보류)
'http://localhost:3000/plan/:id

title recommendPlanSchedule seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Click "약속 일정 추천"

Client -> Server: **GET /groups/:group_id/plans/:plan_id/selection** \n Request "Recommend PlanSchedule"

alt#Gold #Pink internal_error
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" & "result.message"

else #Pink recommendPlanSchedule_NotFound
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **404**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    alt #Gray "일정을 선택할 약속이 존재하지 않습니다."
        User <-- Client: Alert "result.comment" & Redirect "/group/:id"

    else #Gray "해당 그룹이 존재하지 않습니다."
        User <-- Client: Alert "result.comment" & Redirect "/userHome"

    else #Gray "신규 사용자가 존재합니다."
        User <-- Client: Alert "result.comment"
    
    end

else #Pink recommendPlanSchedule_accessDenied
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.message" \n & Redirect "/login"

else #LightYellow newUser_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **303**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Redirect "/initSetting"

else #LightBlue recommendPlanSchedule_success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**,
            candidiate_plan_time: [{
                **start**,
                **end**,
                **day**,
                **time**,
            }, ...]
    end note
    alt #Gray candidiate_plan_time.length === 1
        User <-- Client: Redirect "/group/:id"

    else #Gray candidiate_plan_time.length > 1
        User <-- Client: Redirect "/candidatePick/:id"
    end

end

@enduml