@startuml individualSchedule
'http://localhost:3000/plan/:id

title individualSchedule seqeunce diagram

skinparam SequenceMessageAlignment center

participant Server order 30
participant Client order 20
actor User order 10

User -> Client: Click "제출 일정 확인"

Client -> Server: **GET /groups/:group_id/plans/:plan_id/schedule/:user_id** \n Request "Read individualSchedule"

alt#Gold #Pink Failure
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **404** or **500**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/userHome"

else #Pink Failure_redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **401**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.message" \n & Redirect "/login"

else #LightYellow Redirect
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **303**,
            comment: "**error comment**",
            message: "**error message**"
    end note
    User <-- Client: Alert "result.comment" \n & Redirect "/initSetting"

else #LightBlue Success
    Client <-- Server: Reponse "JSON"
    note left
        result:
            statusCode: **200**,
            submission:
                **id**,
                **user_id**,
                **plan_id**,
                **submission_time_slot**
    end note

end

@enduml